baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "HugoCast"
theme = "castanet"

[params]
copyright_notice = "Copyright 2016 [Matt Stratton](https://www.mattstrattion.io)"
itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"

  [params.social]
    github = "arresteddevops"
    facebook = "Arresteddevops"
    facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
    twitter = "arresteddevops"
    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "ArrestedDevOps"
    pinterest = "nozzleio"
    instagram = "nozzleio"
    youtube = "arresteddevops"
    linkedin = "mattstratton"
